baseURL = "http://example.org/"
languageCode = "es"
defaultContentLanguage = "es"
title = "Brunvelop"
theme = "dreams"

[params]
  #background = "#ccc"
  #backgroundImage = "/me/background.jpg"
  #linkColor = "seagreen"

  # dark mode
  defaultDark = true
  backgroundDark = "black"
  backgroundImageDark = "/me/background-dark.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  images = [""]

  author = "Brunvelop"
  description = "Brunvelop"
  avatar = "/img/Icono.png"
  headerTitle = "Brunvelop"
  motto = "Tecnología Creativa"
  submotto = "Mis últimos proyectos"
  categoriesLimitInHeader = 6
  headerBottomText = ""

  rss = true

  utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "brunvelop@gmail.com"
  twitter = "brunvelop"
  #facebook = "g1eny0ung"
  instagram = "brunvelop"
  # mastodon = ""
  #linkedin = "钺杨g1eny0ung"
  github = "brunvelop"
  #stackoverflow = "5676489/g1eny0ung"
  tiktok = "brunvelop"
  googleplay = "brunvelop"
  youtube = "brunvelop"

  #siteStartYear = 2020

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  #enableSearch = false

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  enableNav = false

  [params.advanced]
    customCSS = ["css/custom.css"]
    customJS = []

  copyMark = false
  categorias = false

  googleAnalytics = "https://www.googletagmanager.com/gtag/js?id=UA-181745464-1"
